//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutreachModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camp
    {
        public Camp()
        {
            this.Patients = new HashSet<Patient>();
            this.camp_patient = new HashSet<camp_patient>();
        }
    
        public int Id { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string location_1 { get; set; }
        public string location_2 { get; set; }
        public string organizer { get; set; }
        public string contact_person { get; set; }
        public string contact_number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<camp_patient> camp_patient { get; set; }
    }
}
