//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutreachModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamComplaint
    {
        public int Id { get; set; }
        public int examinationId { get; set; }
        public string eye { get; set; }
        public string complaint { get; set; }
        public string otherComplaint { get; set; }
        public string group { get; set; }
    
        public virtual Examination Examination { get; set; }
    }
}
