//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutreachModule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refraction
    {
        public int Id { get; set; }
        public string eye { get; set; }
        public int e2Id { get; set; }
        public double sph { get; set; }
        public double cyl { get; set; }
        public double axis { get; set; }
    
        public virtual E2 E2 { get; set; }
    }
}
